use super::{ModelEntry, ProviderDescriptor};

pub(super) const PROVIDER_KEYS: &[&str] = &[
    "dashscope",
    "dashscope_token_plan",
    "openai",
    "anthropic",
    "deepseek",
    "openapi_compatible",
    "anthropic_compatible",
    "gemini",
    "kimi_cn",
    "kimi_intl",
    "minimax_cn",
    "minimax_intl",
    "zhipu_cn",
    "zhipu_intl",
    "volcengine_cn",
    "siliconflow_cn",
    "siliconflow_intl",
    "ollama",
    "lmstudio",
    "openrouter",
    "azure_openai",
    "modelscope",
    "aliyun_codingplan",
    "aliyun_codingplan_intl",
    "zhipu_cn_codingplan",
    "zhipu_intl_codingplan",
    "volcengine_cn_codingplan",
];

pub(super) fn provider_descriptor(key: &str) -> Option<ProviderDescriptor> {
    Some(match key {
        "dashscope" => descriptor(
            key,
            "DashScope",
            "Alibaba Cloud Bailian",
            Some("https://dashscope.aliyuncs.com/compatible-mode/v1"),
            &[
                model("qwen3.7-max", true, false),
                model("qwen3.7-plus", false, true),
                model("qwen3.6-plus", false, true),
                model("qwen3.6-max-preview", false, false),
                model("qwen3-max", false, false),
                model("qwen3.5-plus", false, true),
                model("qwen3.5-flash", false, false),
                model("qwq-plus", false, false),
                model("qwen3-coder-plus", false, false),
                model("kimi-k2.6", false, true),
                model("deepseek-v4-pro", false, false),
                model("deepseek-v4-flash", false, false),
                model("glm-5.1", false, false),
            ],
            true,
            false,
            true,
        ),
        "dashscope_token_plan" => descriptor(
            key,
            "DashScope Token Plan",
            "Alibaba Cloud Bailian Token Plan",
            Some("https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1"),
            &[
                model("qwen3.6-plus", true, true),
                model("qwen3.6-flash", false, false),
                model("deepseek-v4-pro", false, false),
                model("deepseek-v4-flash", false, false),
                model("deepseek-v3.2", false, false),
                model("glm-5.1", false, false),
                model("glm-5", false, false),
                model("MiniMax-M2.5", false, false),
                model("kimi-k2.5", false, true),
                model("kimi-k2.6", false, true),
            ],
            true,
            false,
            true,
        ),
        "openai" => descriptor(
            key,
            "OpenAI",
            "OpenAI",
            None,
            &[
                model("gpt-5.5", true, true),
                model("gpt-5.4", false, true),
                model("gpt-5.4-mini", false, true),
                model("gpt-5.3-codex", false, true),
                model("gpt-5.2", false, true),
                model("o3", false, true),
                model("o4-mini", false, true),
            ],
            true,
            false,
            false,
        ),
        "anthropic" => descriptor(
            key,
            "Anthropic",
            "Anthropic",
            None,
            &[
                model("claude-opus-4-7", true, true),
                model("claude-opus-4-6", false, true),
                model("claude-sonnet-4-6", false, true),
                model("claude-sonnet-4-6-1m", false, true),
                model("claude-haiku-4-5-20251001", false, true),
            ],
            true,
            false,
            false,
        ),
        "deepseek" => descriptor(
            key,
            "DeepSeek",
            "DeepSeek",
            Some("https://api.deepseek.com/v1"),
            &[
                model("deepseek-v4-pro", true, false),
                model("deepseek-v4-flash", false, false),
            ],
            true,
            false,
            true,
        ),
        "openapi_compatible" => descriptor(
            key,
            "OpenAPI Compatible",
            "OpenAPI Compatible",
            None,
            &[],
            true,
            false,
            false,
        ),
        "anthropic_compatible" => descriptor(
            key,
            "Anthropic Compatible",
            "Anthropic Compatible",
            None,
            &[],
            true,
            false,
            false,
        ),
        "gemini" => descriptor(
            key,
            "Gemini",
            "Google Gemini",
            Some("https://generativelanguage.googleapis.com/v1beta/openai"),
            &[
                model("gemini-3.5-flash", true, true),
                model("gemini-3.1-pro-preview", false, true),
                model("gemini-3-flash-preview", false, true),
                model("gemini-3.1-flash-lite", false, true),
                model("gemini-3.1-flash-lite-preview", false, true),
                model("gemini-2.5-pro", false, true),
                model("gemini-2.5-flash", false, true),
                model("gemini-2.5-flash-lite", false, true),
                model("gemini-2.0-flash", false, true),
            ],
            true,
            false,
            true,
        ),
        "kimi_cn" => descriptor(
            key,
            "Kimi CN",
            "Kimi (China)",
            Some("https://api.moonshot.cn/v1"),
            &[
                model("kimi-k2.6", true, true),
                model("kimi-k2.5", false, true),
            ],
            true,
            false,
            false,
        ),
        "kimi_intl" => descriptor(
            key,
            "Kimi Intl",
            "Kimi (International)",
            Some("https://api.moonshot.ai/v1"),
            &[
                model("kimi-k2.6", true, true),
                model("kimi-k2.5", false, true),
            ],
            true,
            false,
            false,
        ),
        "minimax_cn" => descriptor(
            key,
            "MiniMax CN",
            "MiniMax (China)",
            Some("https://api.minimaxi.com/anthropic"),
            &[
                model("MiniMax-M2.7", true, false),
                model("MiniMax-M2.7-highspeed", false, false),
                model("MiniMax-M2.5", false, false),
                model("MiniMax-M2.5-highspeed", false, false),
            ],
            true,
            false,
            false,
        ),
        "minimax_intl" => descriptor(
            key,
            "MiniMax Intl",
            "MiniMax (International)",
            Some("https://api.minimax.io/anthropic"),
            &[
                model("MiniMax-M2.7", true, false),
                model("MiniMax-M2.7-highspeed", false, false),
                model("MiniMax-M2.5", false, false),
                model("MiniMax-M2.5-highspeed", false, false),
            ],
            true,
            false,
            false,
        ),
        "zhipu_cn" => descriptor(
            key,
            "ZhiPu CN",
            "ZhiPu AI",
            Some("https://open.bigmodel.cn/api/paas/v4"),
            &[
                model("glm-5.1", true, false),
                model("glm-5", false, false),
                model("glm-5-turbo", false, false),
            ],
            true,
            false,
            false,
        ),
        "zhipu_intl" => descriptor(
            key,
            "ZhiPu Intl",
            "ZhiPu AI (International)",
            Some("https://api.z.ai/api/paas/v4"),
            &[
                model("glm-5.1", true, false),
                model("glm-5", false, false),
                model("glm-5-turbo", false, false),
            ],
            true,
            false,
            false,
        ),
        "volcengine_cn" => descriptor(
            key,
            "Volcengine CN",
            "Volcengine",
            Some("https://ark.cn-beijing.volces.com/api/v3"),
            &[
                model("doubao-seed-2-0-code-preview-260215", true, false),
                model("doubao-seed-2-0-pro-260215", false, true),
                model("doubao-seed-2-0-lite-260428", false, false),
            ],
            true,
            false,
            false,
        ),
        "siliconflow_cn" => descriptor(
            key,
            "SiliconFlow CN",
            "SiliconFlow (China)",
            Some("https://api.siliconflow.cn/v1"),
            &[],
            true,
            false,
            false,
        ),
        "siliconflow_intl" => descriptor(
            key,
            "SiliconFlow Intl",
            "SiliconFlow (International)",
            Some("https://api.siliconflow.com/v1"),
            &[],
            true,
            false,
            false,
        ),
        "ollama" => descriptor(
            key,
            "Ollama",
            "Ollama (Local)",
            Some("http://localhost:11434/v1"),
            &[],
            false,
            true,
            false,
        ),
        "lmstudio" => descriptor(
            key,
            "LM Studio",
            "LM Studio (Local)",
            Some("http://localhost:1234/v1"),
            &[],
            false,
            true,
            false,
        ),
        "openrouter" => descriptor(
            key,
            "OpenRouter",
            "OpenRouter",
            Some("https://openrouter.ai/api/v1"),
            &[],
            true,
            false,
            false,
        ),
        "azure_openai" => descriptor(
            key,
            "Azure OpenAI",
            "Azure OpenAI",
            None,
            &[
                model("gpt-5", true, true),
                model("gpt-5-mini", false, true),
                model("gpt-4.1", false, true),
                model("gpt-4o", false, true),
            ],
            true,
            false,
            false,
        ),
        "modelscope" => descriptor(
            key,
            "ModelScope",
            "ModelScope",
            Some("https://api-inference.modelscope.cn/v1"),
            &[model("Qwen/Qwen3.5-122B-A10B", true, false)],
            true,
            false,
            false,
        ),
        "aliyun_codingplan" => codingplan_descriptor(
            key,
            "Aliyun CodingPlan",
            "Alibaba Cloud CodingPlan",
            "https://coding.dashscope.aliyuncs.com/v1",
        ),
        "aliyun_codingplan_intl" => codingplan_descriptor(
            key,
            "Aliyun CodingPlan Intl",
            "Alibaba Cloud CodingPlan (International)",
            "https://coding-intl.dashscope.aliyuncs.com/v1",
        ),
        "zhipu_cn_codingplan" => descriptor(
            key,
            "ZhiPu CN CodingPlan",
            "ZhiPu AI CodingPlan",
            Some("https://open.bigmodel.cn/api/coding/paas/v4"),
            &[model("glm-5.1", true, false), model("glm-5", false, false)],
            true,
            false,
            false,
        ),
        "zhipu_intl_codingplan" => descriptor(
            key,
            "ZhiPu Intl CodingPlan",
            "ZhiPu AI CodingPlan (International)",
            Some("https://api.z.ai/api/coding/paas/v4"),
            &[model("glm-5.1", true, false), model("glm-5", false, false)],
            true,
            false,
            false,
        ),
        "volcengine_cn_codingplan" => descriptor(
            key,
            "Volcengine CodingPlan",
            "Volcengine CodingPlan",
            Some("https://ark.cn-beijing.volces.com/api/coding/v3"),
            &[
                model("doubao-seed-2-0-code-preview-260215", true, false),
                model("doubao-seed-2-0-pro-260215", false, true),
                model("doubao-seed-2-0-lite-260428", false, false),
                model("glm-5.1", false, false),
                model("minimax-m2.7", false, false),
                model("kimi-k2.6", false, true),
                model("kimi-k2.5", false, true),
            ],
            true,
            false,
            false,
        ),
        _ => return None,
    })
}

fn codingplan_descriptor(
    key: &str,
    name: &str,
    display_name: &str,
    base_url: &str,
) -> ProviderDescriptor {
    descriptor(
        key,
        name,
        display_name,
        Some(base_url),
        &[
            model("qwen3.6-plus", true, true),
            model("qwen3.5-plus", false, true),
            model("glm-5", false, false),
            model("glm-4.7", false, false),
            model("MiniMax-M2.5", false, false),
            model("kimi-k2.5", false, true),
            model("qwen3-coder-plus", false, false),
            model("qwen3-coder-next", false, false),
        ],
        true,
        false,
        true,
    )
}

#[allow(clippy::too_many_arguments)]
fn descriptor(
    key: &str,
    name: &str,
    display_name: &str,
    base_url: Option<&str>,
    models: &[ModelEntry],
    require_api_key: bool,
    is_local: bool,
    supports_stream_options: bool,
) -> ProviderDescriptor {
    ProviderDescriptor {
        key: key.to_owned(),
        name: name.to_owned(),
        display_name: display_name.to_owned(),
        base_url: base_url.map(str::to_owned),
        models: models.to_vec(),
        require_api_key,
        is_local,
        supports_stream_options,
    }
}

fn model(id: &str, is_default: bool, support_multimodal: bool) -> ModelEntry {
    ModelEntry {
        id: id.to_owned(),
        is_default,
        support_multimodal,
    }
}
