blank_issues_enabled: true
contact_links:
  - name: DingTalk Group
    url: https://qr.dingtalk.com/action/joingroup?code=v1,k1,ubm/77U7qRh/STFZUNBP26X4PNg2z6+uhiPcLGtDNfU=&_dt_no_comment=1&origin=11
    about: Join our DingTalk group for real-time support and discussion
  - name: Discord
    url: https://discord.gg/qECFuFBwF
    about: Join our Discord server for community support
