#[derive(Clone, Debug)]
pub(crate) struct A2AServerArgs {
    pub(crate) config: String,
    pub(crate) host: String,
    pub(crate) port: u16,
    pub(crate) transport: String,
    pub(crate) socket_path: String,
    pub(crate) ws_path: String,
    pub(crate) grpc_host: String,
    pub(crate) grpc_port: Option<u16>,
    pub(crate) redis_url: String,
    pub(crate) request_stream: String,
    pub(crate) response_stream: String,
    pub(crate) consumer_group: String,
    pub(crate) token: String,
    pub(crate) basic_username: String,
    pub(crate) basic_password: String,
    pub(crate) api_key: String,
    pub(crate) push_queue: String,
    pub(crate) push_redis_url: String,
    pub(crate) push_stream: String,
    pub(crate) push_retry_key: String,
    pub(crate) push_dead_stream: String,
    pub(crate) push_consumer_group: String,
    pub(crate) push_consumer_name: String,
    pub(crate) push_lease_timeout_ms: u64,
    pub(crate) api_key_header: String,
    pub(crate) push_notifications: bool,
    pub(crate) signing_secret: String,
    pub(crate) persistence_dir: String,
    pub(crate) artifact_dir: String,
    pub(crate) auto_approve_permissions: bool,
    pub(crate) log_to_stdout: bool,
    pub(crate) thinking_exposure: Vec<String>,
}

impl Default for A2AServerArgs {
    fn default() -> Self {
        Self {
            host: "127.0.0.1".to_owned(),
            port: 41242,
            transport: "http".to_owned(),
            push_queue: "local-file".to_owned(),
            api_key_header: "X-API-Key".to_owned(),
            config: String::new(),
            socket_path: String::new(),
            ws_path: "/a2a".to_owned(),
            grpc_host: String::new(),
            grpc_port: None,
            redis_url: String::new(),
            request_stream: "iac-code:a2a:requests".to_owned(),
            response_stream: "iac-code:a2a:responses".to_owned(),
            consumer_group: "iac-code".to_owned(),
            token: String::new(),
            basic_username: String::new(),
            basic_password: String::new(),
            api_key: String::new(),
            push_redis_url: String::new(),
            push_stream: "iac-code:a2a:push".to_owned(),
            push_retry_key: "iac-code:a2a:push:retry".to_owned(),
            push_dead_stream: "iac-code:a2a:push:dead".to_owned(),
            push_consumer_group: "iac-code-push".to_owned(),
            push_consumer_name: String::new(),
            push_lease_timeout_ms: 300_000,
            push_notifications: false,
            signing_secret: String::new(),
            persistence_dir: String::new(),
            artifact_dir: String::new(),
            auto_approve_permissions: false,
            log_to_stdout: false,
            thinking_exposure: Vec::new(),
        }
    }
}
