.PHONY: dev build serve clean install

install: ## Install dependencies
	npm install

dev: ## Run documentation site locally
	npm run start

build: ## Build documentation site
	npm run build

serve: ## Serve built documentation site locally
	npm run serve

clean: ## Remove build artifacts
	rm -rf build .docusaurus .cache-loader
